CREATE OR REPLACE TABLE CUSTOMER360.PUBLIC.MARKETING_DATA (
    ID INT,
    YEAR_BIRTH INT,
    EDUCATION STRING,
    MARITAL_STATUS STRING,
    INCOME FLOAT,
    KIDHOME INT,
    TEENHOME INT,
    DT_CUSTOMER DATE,
    RECENCY INT,
    MNTWINES FLOAT,
    MNTFRUITS FLOAT,
    MNTMEATPRODUCTS FLOAT,
    MNTFISHPRODUCTS FLOAT,
    MNTSWEETPRODUCTS FLOAT,
    MNTGOLDPRODS FLOAT,
    NUMDEALSPURCHASES INT,
    NUMWEBPURCHASES INT,
    NUMCATALOGPURCHASES INT,
    NUMSTOREPURCHASES INT,
    NUMWEBVISITSMONTH INT,
    ACCEPTEDCMP3 INT,
    ACCEPTEDCMP4 INT,
    ACCEPTEDCMP5 INT,
    ACCEPTEDCMP1 INT,
    ACCEPTEDCMP2 INT,
    COMPLAIN INT,
    Z_COSTCONTACT INT,
    Z_REVENUE INT,
    RESPONSE INT
);
-- ===== NEXT QUERY =====

SHOW TABLES IN CUSTOMER360.PUBLIC;

-- ===== NEXT QUERY =====

SELECT
  *
FROM
  "CUSTOMER360"."PUBLIC"."CUSTOMER_DATA"
LIMIT
  10;

-- ===== NEXT QUERY =====

SELECT COUNT(*) FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA;

-- ===== NEXT QUERY =====

SELECT MARITAL_STATUS, AVG(INCOME) AS AVG_INCOME
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
GROUP BY MARITAL_STATUS;

-- ===== NEXT QUERY =====

SELECT EDUCATION, COUNT(*) AS NUM_CUSTOMERS
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
GROUP BY EDUCATION
ORDER BY NUM_CUSTOMERS DESC;

-- ===== NEXT QUERY =====

SELECT 
    CASE 
        WHEN YEAR_BIRTH <= 1970 THEN '50+ Years'
        WHEN YEAR_BIRTH BETWEEN 1971 AND 1985 THEN '36–50 Years'
        WHEN YEAR_BIRTH BETWEEN 1986 AND 2000 THEN '20–35 Years'
        ELSE 'Below 20'
    END AS AGE_GROUP,
    ROUND(AVG(INCOME), 2) AS AVG_INCOME,
    COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
WHERE INCOME IS NOT NULL
GROUP BY AGE_GROUP
ORDER BY AVG_INCOME DESC;

-- ===== NEXT QUERY =====
SELECT 
    CASE 
        WHEN YEAR_BIRTH <= 1970 THEN '50+ Years'
        WHEN YEAR_BIRTH BETWEEN 1971 AND 1985 THEN '36–50 Years'
        WHEN YEAR_BIRTH BETWEEN 1986 AND 2000 THEN '20–35 Years'
        ELSE 'Below 20'
    END AS AGE_GROUP,
    ROUND(AVG(INCOME), 2) AS AVG_INCOME,
    COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
WHERE INCOME IS NOT NULL
GROUP BY AGE_GROUP
ORDER BY AVG_INCOME DESC;

-- ===== NEXT QUERY =====

SELECT 
    'Wines' AS CATEGORY, SUM(MNTWINES) AS TOTAL_SPEND FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
UNION ALL
SELECT 'Meat Products', SUM(MNTMEATPRODUCTS) FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
UNION ALL
SELECT 'Fish Products', SUM(MNTFISHPRODUCTS) FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
UNION ALL
SELECT 'Sweet Products', SUM(MNTSWEETPRODUCTS) FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
UNION ALL
SELECT 'Gold Products', SUM(MNTGOLDPRODS) FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
ORDER BY TOTAL_SPEND DESC;

-- ===== NEXT QUERY =====

SELECT 
    ROUND(100.0 * SUM(CASE WHEN ACCEPTEDCMP1=1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS CMP1_SUCCESS_RATE,
    ROUND(100.0 * SUM(CASE WHEN ACCEPTEDCMP2=1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS CMP2_SUCCESS_RATE,
    ROUND(100.0 * SUM(CASE WHEN ACCEPTEDCMP3=1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS CMP3_SUCCESS_RATE,
    ROUND(100.0 * SUM(CASE WHEN ACCEPTEDCMP4=1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS CMP4_SUCCESS_RATE,
    ROUND(100.0 * SUM(CASE WHEN ACCEPTEDCMP5=1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS CMP5_SUCCESS_RATE,
    ROUND(100.0 * SUM(CASE WHEN RESPONSE=1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS OVERALL_SUCCESS_RATE
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA;

-- ===== NEXT QUERY =====

SELECT 
    ROUND(AVG(NUMWEBPURCHASES),2) AS AVG_WEB_PURCHASES,
    ROUND(AVG(NUMCATALOGPURCHASES),2) AS AVG_CATALOG_PURCHASES,
    ROUND(AVG(NUMSTOREPURCHASES),2) AS AVG_STORE_PURCHASES
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA;

-- ===== NEXT QUERY =====

WITH CUSTOMER_SPEND AS (
    SELECT 
        ID,
        (MNTWINES + MNTFRUITS + MNTMEATPRODUCTS + MNTFISHPRODUCTS + MNTSWEETPRODUCTS + MNTGOLDPRODS) AS TOTAL_SPEND
    FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
)
SELECT 
    ID,
    ROUND(TOTAL_SPEND,2) AS TOTAL_SPEND
FROM CUSTOMER_SPEND
WHERE TOTAL_SPEND >= (
    SELECT PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY TOTAL_SPEND) FROM CUSTOMER_SPEND
)
ORDER BY TOTAL_SPEND DESC;


-- ===== NEXT QUERY =====

SELECT 
    ID,
    RECENCY,
    (MNTWINES + MNTFRUITS + MNTMEATPRODUCTS + MNTFISHPRODUCTS + MNTSWEETPRODUCTS + MNTGOLDPRODS) AS TOTAL_SPEND,
    CASE 
        WHEN RECENCY <= 30 THEN 'Highly Active'
        WHEN RECENCY BETWEEN 31 AND 90 THEN 'Moderately Active'
        ELSE 'Dormant'
    END AS RECENCY_SEGMENT
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
ORDER BY TOTAL_SPEND DESC;

-- ===== NEXT QUERY =====

SELECT 
    CASE 
        WHEN INCOME < 30000 THEN 'Low Income'
        WHEN INCOME BETWEEN 30000 AND 60000 THEN 'Mid Income'
        ELSE 'High Income'
    END AS INCOME_GROUP,
    ROUND(100.0 * SUM(CASE WHEN RESPONSE = 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS RESPONSE_RATE,
    COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
WHERE INCOME IS NOT NULL
GROUP BY INCOME_GROUP
ORDER BY RESPONSE_RATE DESC;

-- ===== NEXT QUERY =====

SELECT 
    MARITAL_STATUS,
    ROUND(AVG(MNTWINES),2) AS AVG_WINE_SPEND,
    ROUND(AVG(MNTMEATPRODUCTS),2) AS AVG_MEAT_SPEND,
    ROUND(AVG(MNTFISHPRODUCTS),2) AS AVG_FISH_SPEND,
    ROUND(AVG(MNTSWEETPRODUCTS),2) AS AVG_SWEET_SPEND
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
GROUP BY MARITAL_STATUS
ORDER BY AVG_WINE_SPEND DESC;

-- ===== NEXT QUERY =====

SELECT 
    ID,
    NUMWEBPURCHASES,
    NUMCATALOGPURCHASES,
    NUMSTOREPURCHASES,
    (NUMWEBPURCHASES + NUMCATALOGPURCHASES + NUMSTOREPURCHASES) AS TOTAL_PURCHASES,
    CASE 
        WHEN NUMWEBPURCHASES > NUMCATALOGPURCHASES 
             AND NUMWEBPURCHASES > NUMSTOREPURCHASES THEN 'Web Heavy'
        WHEN NUMCATALOGPURCHASES > NUMWEBPURCHASES 
             AND NUMCATALOGPURCHASES > NUMSTOREPURCHASES THEN 'Catalog Heavy'
        WHEN NUMSTOREPURCHASES > NUMWEBPURCHASES 
             AND NUMSTOREPURCHASES > NUMCATALOGPURCHASES THEN 'Store Heavy'
        ELSE 'Balanced'
    END AS PURCHASE_TYPE
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
ORDER BY TOTAL_PURCHASES DESC;

-- ===== NEXT QUERY =====

SELECT 
    EDUCATION,
    MARITAL_STATUS,
    ROUND(AVG(INCOME),2) AS AVG_INCOME,
    ROUND(AVG(MNTWINES + MNTFRUITS + MNTMEATPRODUCTS + MNTFISHPRODUCTS + MNTSWEETPRODUCTS + MNTGOLDPRODS),2) AS AVG_TOTAL_SPEND,
    COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMER360.PUBLIC.CUSTOMER_DATA
GROUP BY EDUCATION, MARITAL_STATUS
ORDER BY AVG_TOTAL_SPEND DESC
LIMIT 5;
